[project]
name = "event_management"
authors = [
    { name = "Prashant Gaikwad", email = "prashantgaikwad-kc@users.noreply.github.com" }
]
description = "Event Management Platform for organizers, attendees, and gate staff"
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]

dependencies = [
    # QR generation
    "qrcode>=7.4",
    "Pillow>=10.0",
]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.bench.dev-dependencies]

[tool.bench.frappe-dependencies]
frappe = ">=15.0.0,<17.0.0"
